-- =============================================================================
-- NACTVET ICT Inventory Management System
-- Database creation script (PostgreSQL)
-- -----------------------------------------------------------------------------
-- How the database was created (reference / documentation script).
--
-- In normal operation the schema is NOT created from this file by the
-- application at runtime. Instead it is derived from the JPA entities and
-- applied by Hibernate via `spring.jpa.hibernate.ddl-auto: update`
-- (see src/main/resources/application.yaml). This script documents the exact
-- DDL that Hibernate produces for the current entity model, plus the
-- `employee_id_seq` and initial ADMIN seed row, so the database can be
-- recreated manually from scratch and kept in sync with the code.
--
-- The purpose of this file is purely to SHOW how the database was created.
-- The runtime-managed schema migration script is src/main/resources/schema.sql
-- (with the "@@" statement separator, see application.yaml), which handles the
-- ALTER/DROP transitions between model versions.
--
-- Connection (application.yaml):
--   url       : jdbc:postgresql://localhost:5439/ict_inventory
--   username  : postgres
--   password  : Inventory123
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Create the database (run as a privileged superuser, e.g. postgres)
-- ---------------------------------------------------------------------------
-- CREATE DATABASE ict_inventory
--     WITH OWNER = postgres
--          ENCODING = 'UTF8'
--          TEMPLATE = template0
--          LC_COLLATE = 'en_US.UTF-8'
--          LC_CTYPE = 'en_US.UTF-8'
--          CONNECTION LIMIT = -1;
--
-- (commented out: running CREATE DATABASE inside a transaction / within the
--  managed datasource is not allowed. Connect to the `postgres` database first
--  and execute the statement manually.)

\connect ict_inventory;

-- ---------------------------------------------------------------------------
-- 2. Sequence used by EmployeeIdGenerator to create unique Employee IDs
--    (format NCT-EMP-00001, ...). Same statement as in schema.sql; created
--    before Hibernate so it exists at registration time.
-- ---------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS employee_id_seq;

-- ===========================================================================
-- TABLES (generated by Hibernate 6 from the JPA entities)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Zones (a zone contains many offices)
-- ---------------------------------------------------------------------------
CREATE TABLE zones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    code        VARCHAR(255) UNIQUE,
    description TEXT,
    status      VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ---------------------------------------------------------------------------
-- Offices (belong to a zone, identified by office code within that zone)
-- ---------------------------------------------------------------------------
CREATE TABLE offices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id     BIGINT NOT NULL REFERENCES zones (id),
    office_code VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_offices_zone_code UNIQUE (zone_id, office_code)
);

CREATE INDEX idx_offices_zone_id ON offices (zone_id);

-- ---------------------------------------------------------------------------
-- Directorates (top-level organisational unit a user belongs to)
-- ---------------------------------------------------------------------------
CREATE TABLE directorates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    code        VARCHAR(255) UNIQUE,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ---------------------------------------------------------------------------
-- Sections (belong to a directorate)
-- ---------------------------------------------------------------------------
CREATE TABLE sections (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    code           VARCHAR(255) UNIQUE,
    description    TEXT,
    directorate_id BIGINT NOT NULL REFERENCES directorates (id),
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_sections_directorate_id ON sections (directorate_id);

-- ---------------------------------------------------------------------------
-- Units (a user belongs to a unit)
-- ---------------------------------------------------------------------------
CREATE TABLE units (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    code        VARCHAR(255) UNIQUE,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ---------------------------------------------------------------------------
-- Device types (asset categories)
-- ---------------------------------------------------------------------------
CREATE TABLE device_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ---------------------------------------------------------------------------
-- Users
-- NOTE: A User does NOT have a zone/office (they belong to the Asset location).
--       role is stored as a string (enum): ADMIN.
--       username is kept internally on the entity and equals the email
--       (email is the public login/username); it is excluded from all DTOs.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     VARCHAR(255) NOT NULL UNIQUE,
    full_name       VARCHAR(255) NOT NULL,
    username        VARCHAR(255) NOT NULL UNIQUE,
    email           VARCHAR(255) UNIQUE,
    password        VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(255),
    role            VARCHAR(255) NOT NULL,
    enabled         BOOLEAN NOT NULL,
    setup_completed BOOLEAN NOT NULL DEFAULT FALSE,
    directorate_id  BIGINT REFERENCES directorates (id),
    section_id      BIGINT REFERENCES sections (id),
    unit_id         BIGINT REFERENCES units (id),
    created_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_users_directorate_id ON users (directorate_id);
CREATE INDEX idx_users_section_id     ON users (section_id);
CREATE INDEX idx_users_unit_id        ON users (unit_id);

-- ---------------------------------------------------------------------------
-- Assets
-- A User (owner/staff) belongs to directorate/section/unit, while an Asset
-- carries its PHYSICAL location as zone + office code (entered as freeform text).
-- ---------------------------------------------------------------------------
CREATE TABLE assets (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_number      VARCHAR(255) UNIQUE,
    serial_number     VARCHAR(255) UNIQUE,
    device_name       VARCHAR(255) NOT NULL,
    ownership_type    VARCHAR(255) NOT NULL,   -- OFFICE, PERSONAL
    device_status     VARCHAR(255) NOT NULL,   -- ACTIVE, DEFECTIVE
    device_type_id    BIGINT NOT NULL REFERENCES device_types (id),
    user_id           BIGINT NOT NULL REFERENCES users (id),
    zone_id           BIGINT REFERENCES zones (id),
    office               VARCHAR(100) NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_assets_user_id              ON assets (user_id);
CREATE INDEX idx_assets_device_type_id       ON assets (device_type_id);
CREATE INDEX idx_assets_zone_id              ON assets (zone_id);
CREATE INDEX idx_assets_device_status        ON assets (device_status);

-- ---------------------------------------------------------------------------
-- Audit logs
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action                VARCHAR(255) NOT NULL,
    entity_type           VARCHAR(255) NOT NULL,
    entity_id             BIGINT,
    performed_by          VARCHAR(255),
    performed_by_user_id  BIGINT,
    description           TEXT,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- ===========================================================================
-- NOT NULL columns that Hibernate adds with a default are documented here for
-- completeness (already reflected above via DEFAULT clauses).
-- ===========================================================================

-- ===========================================================================
-- Seed data (mirrors DataInitializer.java / DataInitializer expects a bcrypt-
-- encoded password; the placeholder below is replaced by the app on startup).
-- ===========================================================================
-- INSERT INTO users
--     (employee_id, full_name, username, email, password, role, enabled,
--      setup_completed, created_at, updated_at)
-- VALUES
--     ('EMP001', 'System Administrator', 'admin', 'admin@nactvet.go.tz',
--      '<bcrypt-encoded-password>', 'ADMIN', TRUE, TRUE, NOW(), NOW());
--
-- NOTE: The ADMIN user is actually created at runtime by DataInitializer using
-- a password from application.yaml (app.admin.*). The default admin login is
--   username: admin
--   email   : admin@nactvet.go.tz
--   password: admin123   (CHANGE THIS IN PRODUCTION)

-- ===========================================================================
-- STAFF + ASSET seed (DataSeedInitializer)
-- ---------------------------------------------------------------------------
-- At runtime, src/main/java/.../config/DataSeedInitializer (a CommandLineRunner,
-- which runs AFTER the MasterDataInitializer ApplicationRunner) idempotently
-- seeds the following: 
--
--   11 device types: Laptop, Desktop Computer, Projector, Photocopier,
--                    Printer, Scanner, Monitor, Network Switch,
--                    Wireless Access Point, UPS, Server
--
--   30 STAFF users   (:password is the shared default Password@123):
--      users 1-24 -> 3 per section across the 8 sections:
--          Registration and Accreditation, Labour Market Analysis and
--          Curriculum Development, Admission, Examinations and Certification,
--          Academic Quality Audit, Compliance and Enforcement, Human Resource
--          Management and Administration, Planning, Monitoring and Evaluation
--      users 25-30 -> one per unit:
--          Information and Communication Technology, Finance and Accounts,
--          Procurement Management, Internal Audit, Communications and
--          Marketing, Legal Services
--
--   150 assets       (5 per staff user, NCT-ICT-XXX-YY / NCTSER-XXX-YY)
--      spread across the 8 zones.
--
-- All staff share the SAME BCrypt hash for Password@123 (see the constant
-- STAFF_PASSWORD_HASH in DataSeedInitializer.java):
--   $2a$10$I8Dj5GFOkhr//MiDv1Sj4.KNymXymuNSluIdpteuqyayEVV.MmPb2
--
-- Seeding is skipped if the master data (sections/units/zones/device types)
-- is not fully present (e.g. on H2 test runs) or if STAFF users already exist.
-- ===========================================================================

-- ===========================================================================
-- Runtime migration file (schema.sql) applies post-creation model changes:
--   - Schema DDL generated by Hibernate 6. For MySQL/Derby it may differ
--     slightly (e.g. boolean as TINYINT/BOOLEAN). This file documents the
--     PostgreSQL layout used by the application.
-- ===========================================================================
